### ISSUE TITLE
openblas requirement

### ISSUE THREAD

**Issue by PetitLepton** [conda-forge/pymc-feedstock#1]
Hi,

I am trying to install `pymc` from conda on the `osx-64` platform. Here is the list of packages installed
```
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::appnope=0.1.0=py35_0
- conda-forge::bleach=1.5.0=py35_0
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py35_0
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::decorator=4.0.11=py35_0
- conda-forge::entrypoints=0.2.2=py35_1
- conda-forge::freetype=2.7=1
- conda-forge::html5lib=0.999=py35_0
- conda-forge::icu=58.1=1
- conda-forge::ipykernel=4.5.2=py35_0
- conda-forge::ipython=5.3.0=py35_0
- conda-forge::ipython_genutils=0.2.0=py35_0
- conda-forge::ipywidgets=6.0.0=py35_0
- conda-forge::jinja2=2.9.5=py35_0
- conda-forge::jpeg=9b=0
- conda-forge::jsonschema=2.5.1=py35_0
- conda-forge::jupyter=1.0.0=py35_0
- conda-forge::jupyter_client=5.0.0=py35_0
- conda-forge::jupyter_console=5.1.0=py35_0
- conda-forge::jupyter_core=4.3.0=py35_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libpng=1.6.28=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::markupsafe=0.23=py35_1
- conda-forge::matplotlib=2.0.0=np111py35_2
- conda-forge::mistune=0.7.3=py35_1
- conda-forge::nb_conda=2.0.0=py35_0
- conda-forge::nb_conda_kernels=2.0.0=py35_0
- conda-forge::nbconvert=5.1.1=py35_0
- conda-forge::nbformat=4.2.0=py35_0
- conda-forge::ncurses=5.9=10
- conda-forge::notebook=4.4.1=py35_0
- conda-forge::openssl=1.0.2h=3
- conda-forge::pandas=0.19.2=np111py35_1
- conda-forge::pandoc=1.19.2=0
- conda-forge::pandocfilters=1.4.1=py35_0
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pip=9.0.1=py35_0
- conda-forge::prompt_toolkit=1.0.13=py35_0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pygments=2.2.0=py35_0
- conda-forge::pymc=2.3.6=np111py35_0
- conda-forge::pyparsing=2.2.0=py35_0
- conda-forge::pyqt=4.11.4=py35_2
- conda-forge::python=3.5.3=1
- conda-forge::python-dateutil=2.6.0=py35_0
- conda-forge::pytz=2016.10=py35_0
- conda-forge::pyzmq=16.0.2=py35_1
- conda-forge::qt=4.8.7=7
- conda-forge::qtconsole=4.2.1=py35_1
- conda-forge::readline=6.2=0
- conda-forge::setuptools=33.1.1=py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::sip=4.18=py35_1
- conda-forge::six=1.10.0=py35_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::terminado=0.6=py35_0
- conda-forge::testpath=0.3=py35_0
- conda-forge::tk=8.5.19=1
- conda-forge::tornado=4.4.2=py35_0
- conda-forge::traitlets=4.3.2=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::webencodings=0.5=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::widgetsnbextension=2.0.0=py35_0
- conda-forge::xz=5.2.2=0
- conda-forge::zeromq=4.2.1=1
- conda-forge::zlib=1.2.11=0
- mkl=2017.0.1=0
- numpy=1.11.3=py35_0
- scipy=0.19.0=np111py35_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.13
```

While importing the `pymc` module, I stumbled upon this problem:
```python
Python 3.5.3 | packaged by conda-forge | (default, Feb 10 2017, 07:09:50) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pymc
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

/Users/PetitLepton/miniconda3/envs/analytics/lib/python3.5/site-packages/pymc/__init__.py in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

/Users/PetitLepton/miniconda3/envs/analytics/lib/python3.5/site-packages/pymc/CommonDeterministics.py in <module>()
     19 import inspect
     20 import types
---> 21 from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
     22 from copy import copy
     23 import sys

/Users/PetitLepton/miniconda3/envs/analytics/lib/python3.5/site-packages/pymc/utils.py in <module>()
     12 from copy import copy
     13 from .PyMCObjects import Variable
---> 14 from . import flib
     15 import pdb
     16 from numpy.linalg.linalg import LinAlgError

ImportError: dlopen(/Users/PetitLepton/miniconda3/envs/analytics/lib/python3.5/site-packages/pymc/flib.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/PetitLepton/miniconda3/envs/analytics/lib/python3.5/site-packages/pymc/flib.cpython-35m-darwin.so
  Reason: image not found
```

It seems that `pymc` requires openblas (it does work after installing it) but it is not part of the required packages during installation.

**Comment by PetitLepton** [comment]
If I start from scratch, see the list below, I do not have the problem.

```
name: ds-metrics
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates=2017.1.23=0
- certifi=2017.1.23=py35_0
- cycler=0.10.0=py35_0
- freetype=2.7=1
- libgfortran=3.0.0=0
- libpng=1.6.28=0
- matplotlib=2.0.0=np111py35_3
- ncurses=5.9=10
- openssl=1.0.2h=3
- pip=9.0.1=py35_0
- pymc=2.3.6=np111py35_0
- pyparsing=2.2.0=py35_0
- python=3.5.3=1
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- readline=6.2=0
- setuptools=33.1.1=py35_0
- six=1.10.0=py35_1
- sqlite=3.13.0=1
- tk=8.5.19=1
- tornado=4.4.2=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.11=0
- mkl=2017.0.1=0
- numpy=1.11.3=py35_0
- scipy=0.19.0=np111py35_0
prefix: /Users/PetitLepton/miniconda3/envs/ds-metrics
```

**Comment by PetitLepton** [comment]
It seems to be something different in fact:
```
PetitLepton @ ~
 python3
Python 3.5.3 | packaged by conda-forge | (default, Feb 10 2017, 07:09:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: dlopen(/Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/flib.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/flib.cpython-35m-darwin.so
  Reason: image not found
>>> 
(pymc) 
PetitLepton @ ~
 ipython3
Python 3.5.0 (default, Sep 23 2015, 04:42:00) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pymc

In [2]: 
```

**Comment by PetitLepton** [comment]
Apparently, there is some problem with `Python 3.5.3`:
```python
(pymc) 
PetitLepton @ ~
 which ipython
/Users/PetitLepton/miniconda3/envs/pymc/bin/ipython

(pymc) 
PetitLepton @ ~
 ipython
Python 3.5.3 | packaged by conda-forge | (default, Feb 10 2017, 07:09:50) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pymc
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

/Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/__init__.py in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

/Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/CommonDeterministics.py in <module>()
     19 import inspect
     20 import types
---> 21 from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
     22 from copy import copy
     23 import sys

/Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/utils.py in <module>()
     12 from copy import copy
     13 from .PyMCObjects import Variable
---> 14 from . import flib
     15 import pdb
     16 from numpy.linalg.linalg import LinAlgError

ImportError: dlopen(/Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/flib.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/PetitLepton/miniconda3/envs/pymc/lib/python3.5/site-packages/pymc/flib.cpython-35m-darwin.so
  Reason: image not found

In [2]: 

```

while it seems to work with `Python 3.5.0`
```python
(pymc) 
PetitLepton @ ~
 which ipython3
/Users/PetitLepton/miniconda3/envs/pymc/bin/ipython3

(pymc) 
PetitLepton @ ~
 ipython3
Python 3.5.0 (default, Sep 23 2015, 04:42:00) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pymc

In [2]: 

```

**Comment by kyleabeauchamp** [comment]
I'm seeing this issue on py36:

```
import pymc as pm
File "~/miniconda2/envs/myenv/lib/python3.6/site-packages/pymc/__init__.py", line 30, in <module>
from .CommonDeterministics import *
File "~/miniconda2/envs/myenv/lib/python3.6/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
File "~/miniconda2/envs/myenv/lib/python3.6/site-packages/pymc/utils.py", line 14, in <module>
from . import flib
ImportError: dlopen(~/miniconda2/envs/myenv/lib/python3.6/site-packages/pymc/flib.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
Referenced from: ~/miniconda2/envs/myenv/lib/python3.6/site-packages/pymc/flib.cpython-36m-darwin.so
Reason: image not found
```

**Comment by kyleabeauchamp** [comment]
Based on issues discussed elsewhere (https://github.com/conda-forge/numpy-feedstock/issues/47), I tried adjusting my channel priorities and `conda update --all`, neither of which worked.

**Comment by kyleabeauchamp** [comment]
I was able to work around this by:

1.  `conda env create env.yml` to build environment from scratch
2.  `conda update --all` to update several key dependencies, pulling from conda-forge
3.  `pip install pymc` to build pymc from pypi

This workflow defeats the purpose of using conda, however.

**Comment by fonnesbeck** [comment]
So, is this tied to Py3.5?

**Comment by kyleabeauchamp** [comment]
No, I saw the issue on py36 as well

**Comment by fonnesbeck** [comment]
But, given your solution, if we create new builds with updated dependencies, it should fix the issue?

**Comment by kyleabeauchamp** [comment]
I believe so, but I'm not certain as I'm not as conversant with the conda-forge details as I'd like to be.

**Comment by ocefpaf** [comment]
Closing this as stale.
