### ISSUE TITLE
Builds are not triggered

### ISSUE THREAD

**Issue by twiecki** [conda-forge/pymc-feedstock#75]
### Comment:

We released 5.2.0 but nothing is getting triggered. The same happened with 5.1.2. CC @maresb

**Comment by ricardoV94** [comment]
5.3 was not triggered either

**Comment by maresb** [comment]
Reference to my previous comment [here](https://github.com/conda-forge/pymc-feedstock/pull/74#issuecomment-1479267247), but more relevant, looking a little bit deeper into the logs [here](https://github.com/regro/cf-scripts/actions/runs/4711792835/jobs/8356380599#step:8:1976):

```
2023-04-16T06:20:14.5170833Z 2023-04-16 06:20:14,516 INFO     conda_forge_tick.auto_tick || VERSION-Version IS MIGRATING pymc:main
2023-04-16T06:20:16.9969826Z error: pathspec '5.3.0_h7fec2f' did not match any file(s) known to git
2023-04-16T06:20:17.1090254Z 2023-04-16 06:20:17,108 INFO     conda_forge_tick.update_recipe.version || selector: None
2023-04-16T06:20:17.1095308Z 2023-04-16 06:20:17,109 INFO     conda_forge_tick.update_recipe.version || jinja2 context: {'version': '5.3.0'}
2023-04-16T06:20:17.1098943Z 2023-04-16 06:20:17,109 INFO     conda_forge_tick.update_recipe.version || evaluated jinja2 vars: {}
2023-04-16T06:20:17.1102506Z 2023-04-16 06:20:17,110 INFO     conda_forge_tick.update_recipe.version || updated jinja2 context: {'version': '5.3.0'}
2023-04-16T06:20:17.1106094Z 2023-04-16 06:20:17,110 INFO     conda_forge_tick.update_recipe.version || url key: url
2023-04-16T06:20:17.1109422Z 2023-04-16 06:20:17,110 INFO     conda_forge_tick.update_recipe.version || hash key: sha256
2023-04-16T06:20:17.1113208Z 2023-04-16 06:20:17,111 INFO     conda_forge_tick.update_recipe.version || hashing URL template: https://pypi.io/packages/source/p/pymc/pymc-{{ version }}.tar.gz
2023-04-16T06:20:17.1127612Z 2023-04-16 06:20:17,112 INFO     conda_forge_tick.update_recipe.version || rendered URL: https://pypi.io/packages/source/p/pymc/pymc-5.3.0.tar.gz
2023-04-16T06:20:17.4354979Z 2023-04-16 06:20:17,430 INFO     conda_forge_tick.update_recipe.version || source w/ new hash: {'sha256': '0136fdd48ddeee61b770fc2d4cff4f90a597edc7ce290acea653bfacc3d14fa8',
2023-04-16T06:20:17.4355885Z  'url': 'https://pypi.io/packages/source/p/pymc/pymc-{{ version }}.tar.gz'}
2023-04-16T06:20:17.4357023Z 2023-04-16 06:20:17,431 INFO     conda_forge_tick.update_recipe.version || source w/ new url: {'sha256': '0136fdd48ddeee61b770fc2d4cff4f90a597edc7ce290acea653bfacc3d14fa8',
2023-04-16T06:20:17.4357854Z  'url': 'https://pypi.io/packages/source/p/pymc/pymc-{{ version }}.tar.gz'}
2023-04-16T06:20:17.4358892Z 2023-04-16 06:20:17,431 INFO     conda_forge_tick.update_recipe.version || new URL template: https://pypi.io/packages/source/p/pymc/pymc-{{ version }}.tar.gz
2023-04-16T06:20:17.4359830Z 2023-04-16 06:20:17,431 INFO     conda_forge_tick.update_recipe.version || new URL hash: 0136fdd48ddeee61b770fc2d4cff4f90a597edc7ce290acea653bfacc3d14fa8
2023-04-16T06:20:17.4360831Z 2023-04-16 06:20:17,431 INFO     conda_forge_tick.update_recipe.version || updated|errors: True|set()
2023-04-16T06:20:17.4724489Z 2023-04-16 06:20:17,472 INFO     conda_forge_tick.migrators.dep_updates || bot.inspection: update-grayskull
2023-04-16T06:20:17.4728373Z 2023-04-16 06:20:17,472 INFO     conda_forge_tick.update_deps || making grayskull recipe for pkg pymc-suite w/ version 5.3.0
2023-04-16T06:20:17.6410723Z 2023-04-16 06:20:17,633 ERROR    conda_forge_tick.auto_tick || NON GITHUB ERROR
2023-04-16T06:20:17.6413538Z Traceback (most recent call last):
2023-04-16T06:20:17.6414645Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 1186, in _run_migrator
2023-04-16T06:20:17.6415185Z     migrator_uid, pr_json = run(
2023-04-16T06:20:17.6416007Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 252, in run
2023-04-16T06:20:17.6416602Z     migrator.run_post_piggyback_migrations(recipe_dir, feedstock_ctx.attrs, **kwargs)
2023-04-16T06:20:17.6417585Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/core.py", line 291, in run_post_piggyback_migrations
2023-04-16T06:20:17.6418149Z     mini_migrator.migrate(recipe_dir, attrs, **kwargs)
2023-04-16T06:20:17.6418977Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/migrators/dep_updates.py", line 34, in migrate
2023-04-16T06:20:17.6419733Z     dep_comparison, _ = get_dep_updates_and_hints(
2023-04-16T06:20:17.6420627Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_deps.py", line 63, in get_dep_updates_and_hints
2023-04-16T06:20:17.6421184Z     dep_comparison, gs_recipe = get_grayskull_comparison(
2023-04-16T06:20:17.6422060Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_deps.py", line 205, in get_grayskull_comparison
2023-04-16T06:20:17.6422623Z     gs_recipe = make_grayskull_recipe(attrs, version_key=version_key)
2023-04-16T06:20:17.6423500Z   File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_deps.py", line 165, in make_grayskull_recipe
2023-04-16T06:20:17.6424919Z     recipe, _ = create_python_recipe(
2023-04-16T06:20:17.6437357Z   File "/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/grayskull/__main__.py", line 334, in create_python_recipe
2023-04-16T06:20:17.6437960Z     GrayskullFactory.create_recipe(
2023-04-16T06:20:17.6438836Z   File "/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/grayskull/base/factory.py", line 46, in create_recipe
2023-04-16T06:20:17.6439418Z     GrayskullFactory.REGISTERED_STRATEGY[repo_type.lower()].fetch_data(
2023-04-16T06:20:17.6440314Z   File "/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 60, in fetch_data
2023-04-16T06:20:17.6440882Z     update_recipe(recipe, config, sections or ALL_SECTIONS)
2023-04-16T06:20:17.6461610Z   File "/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 485, in update_recipe
2023-04-16T06:20:17.6467280Z     metadata = get_metadata(recipe, config)
2023-04-16T06:20:17.6468250Z   File "/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 347, in get_metadata
2023-04-16T06:20:17.6468819Z     sdist_metadata, pypi_metadata = get_origin_wise_metadata(config)
2023-04-16T06:20:17.6471810Z   File "/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 231, in get_origin_wise_metadata
2023-04-16T06:20:17.6472376Z     pypi_metadata = get_pypi_metadata(config)
2023-04-16T06:20:17.6484143Z   File "/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/grayskull/strategy/pypi.py", line 255, in get_pypi_metadata
2023-04-16T06:20:17.6484737Z     raise requests.HTTPError(
2023-04-16T06:20:17.6485534Z requests.exceptions.HTTPError: It was not possible to recover package metadata for pymc-suite.
2023-04-16T06:20:17.6486041Z Error code: 404
2023-04-16T06:20:21.3318507Z 2023-04-16 06:20:21,331 INFO     conda_forge_tick.auto_tick || /home/runner/work/cf-scripts/cf-scripts/cf-graph
```

**Comment by ricardoV94** [comment]
@maresb does that log tell you something obvious? 404 is coming from pypi?

**Comment by maresb** [comment]
I need to dig into it more, but my suspicion is that it has to do with the multiple outputs and the `pymc-suite` name. I'd recommend cutting one more release by hand, and then once I find the time I'll go deeper.

**Comment by ricardoV94** [comment]
Latest PyMC didn't trigger again
